# This is a basic workflow to help you get started with Actions

name: webhook

# Controls when the workflow will run
on:
  issues:
  issue_comment:
  label:
  pull_request:
  pull_request_review:
  pull_request_review_comment:
  push:
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: 'json-extended'
          webhook_url: https://3fa9-88-137-66-103.ngrok.io/runner
          webhook_secret: "Y0uR5ecr3t"
          
